# for testing purposes

networks:
  bankapp-test:
    external: true

services:
  bankapp-notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bankapp-notification-service
    ports:
      - "8081:8081"
    networks:
      - bankapp-test
    env_file:
      - ".env.docker"
#  rabbitmq:
#    image: 'rabbitmq:latest'
#    environment:
#      - 'RABBITMQ_DEFAULT_PASS=guest'
#      - 'RABBITMQ_DEFAULT_USER=guest'
#    ports:
#      - '5672'