# application.yaml

spring:
  application:
    name: notification-system
  docker:
    compose:
      enabled: ${SPRING_DOCKER_COMPOSE_ENABLED:false}
      file: ${SPRING_DOCKER_COMPOSE_FILE:./compose-test.yaml}
  rabbitmq:
    username: ${RABBIT_MQ_USER:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}

app:
  send-test-email: ${APP_SEND_TEST_EMAIL:false}
  test-email-address: ${APP_TEST_EMAIL_ADDRESS:testEmail@mackiewicz.info}
  email:
    resend:
      api-key: ${RESEND_API_KEY}
    from-address: ${SENDER_EMAIL_ADDRESS:info@bankapp.mackiewicz.info}

logging:
  level:
    bankapp: ${LOGGING_LEVEL_BANKAPP:INFO}
